name: fruits_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  shared_preferences: ^2.2.3
  sqflite: ^2.4.0    
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/auth/splash1.jpg
    - assets/images/auth/loginscreen.jpg
    - assets/icon/right-arrow.svg
    - assets/icon/google.svg
    - assets/icon/phone.svg
    - assets/logo.svg
  fonts:
    - family: Jost
      fonts:
        - asset: fonts/jost/Jost-Regular.ttf
          weight: 400
        - asset: fonts/jost/Jost-Bold.ttf
          weight: 700
        - asset: fonts/jost/Jost-Medium.ttf
          weight: 500
